cd ~/online-projects || exit
git clone git://github.com/HeinrichApfelmus/reactive-banana.git
git clone git://github.com/benmachine/pointfree.git
git clone git://github.com/bos/criterion.git
git clone git://github.com/fpco/haskell-ide.git
git clone git://github.com/jgm/pandoc.git
git clone git://github.com/kazu-yamamoto/ghc-mod.git
git clone git://github.com/ku-fpg/scotty.git
git clone git://github.com/tanakh/monadius.git
git clone git://github.com/yesodweb/scripts.git
git clone git://github.com/yesodweb/shakespeare.git
git clone http://github.com/bos/snappy
git clone http://github.com/haskell/containers.git
git clone http://github.com/yesodweb/persistent
git clone http://github.com/yesodweb/wai
git clone https://github.com/Gabriel439/Haskell-Errors-Library.git
git clone https://github.com/GaloisInc/HaLVM.git
git clone https://github.com/HeinrichApfelmus/ActiveHs.git
git clone https://github.com/JPMoresmau/BuildWrapper
git clone https://github.com/JPMoresmau/eclipsefp.git
git clone https://github.com/JPMoresmau/scion-class-browser.git
git clone https://github.com/JacquesCarette/GenCheck.git
git clone https://github.com/KentBeck/junit.git
git clone https://github.com/Shougo/neocomplcache.git
git clone https://github.com/Shougo/vimproc.git
git clone https://github.com/Twinside/Juicy.Pixels.git
git clone https://github.com/Twinside/vim-haskellConceal.git
git clone https://github.com/aristidb/http-types
git clone https://github.com/aslatter/qc-instances.git
git clone https://github.com/batterseapower/haskell-kata.git
git clone https://github.com/batterseapower/test-framework.git
git clone https://github.com/bitc/hdevtools.git
git clone https://github.com/bitc/lushtags.git
git clone https://github.com/bitc/vim-hdevtools.git
git clone https://github.com/bos/aeson.git
git clone https://github.com/bos/attoparsec.git
git clone https://github.com/bos/base16-bytestring.git
git clone https://github.com/bos/base64-bytestring.git
git clone https://github.com/bos/mwc-random.git
git clone https://github.com/bos/pronk.git
git clone https://github.com/bos/statistics.git
git clone https://github.com/bos/text.git
git clone https://github.com/caisui/vimperator.git
git clone https://github.com/chrisdone/ji.git
git clone https://github.com/clojure/clojure.git
git clone https://github.com/creswick/cabal-dev.git
git clone https://github.com/dag/vim2hs.git
git clone https://github.com/eagletmt/ghcmod-vim.git
git clone https://github.com/egonSchiele/robot-fruit-hunt.git
git clone https://github.com/ekmett/constraints.git
git clone https://github.com/ekmett/lens.git
git clone https://github.com/evancz/Elm.git
git clone https://github.com/faylang/fay-server.git
git clone https://github.com/faylang/fay.git
git clone https://github.com/ghc/haddock.git
git clone https://github.com/git/git.git
git clone https://github.com/guard/guard-autorefresh.git
git clone https://github.com/guard/guard-shell.git
git clone https://github.com/guard/guard.git
git clone https://github.com/haskell/cabal/
git clone https://github.com/hdbc/hdbc.git
git clone https://github.com/hspec/hspec.git
git clone https://github.com/igstan/learn-you-some-erlang-kindle.git
git clone https://github.com/jaspervdj/digestive-functors.git
git clone https://github.com/jaspervdj/stylish-haskell.git
git clone https://github.com/jonsterling/Data.Records.git
git clone https://github.com/kallisti-dev/hs-webdriver.git
git clone https://github.com/kazu-yamamoto/logger.git
git clone https://github.com/kfish/const-math-ghc-plugin.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/kolmodin/binary.git
git clone https://github.com/leepike/SmartCheck.git
git clone https://github.com/lmartinking/tmux-applets.git
git clone https://github.com/logankoester/autorefresh.git
git clone https://github.com/lpsmith/postgresql-libpq.git
git clone https://github.com/lpsmith/postgresql-simple.git
git clone https://github.com/m4dc4p/haskelldb
git clone https://github.com/marcotmarcot/chuchu.git
git clone https://github.com/meteficha/esqueleto.git
git clone https://github.com/mezzohaskell/mezzohaskell.git
git clone https://github.com/milkbikis/powerline-bash
git clone https://github.com/msanders/snipmate.vim.git
git clone https://github.com/philc/vimium.git
git clone https://github.com/pufuwozu/roy.git
git clone https://github.com/remiprev/teamocil.git
git clone https://github.com/sebastiaanvisser/fclabels.git
git clone https://github.com/shayan-najd/HTE.git
git clone https://github.com/simonmar/async
git clone https://github.com/simonmar/monad-par.git
git clone https://github.com/simonmar/par-tutorial.git
git clone https://github.com/skogsbaer/HTF.git
git clone https://github.com/snapframework/snap.git
git clone https://github.com/snoyberg/basic-prelude.git
git clone https://github.com/snoyberg/classy-prelude.git
git clone https://github.com/snoyberg/conduit.git
git clone https://github.com/snoyberg/elm-yesod.git
git clone https://github.com/snoyberg/haskellers.git
git clone https://github.com/snoyberg/http-conduit.git
git clone https://github.com/snoyberg/json2yaml.git
git clone https://github.com/snoyberg/keter.git
git clone https://github.com/snoyberg/markdown.git
git clone https://github.com/snoyberg/todolist.git
git clone https://github.com/snoyberg/whosawthatcoming.git
git clone https://github.com/snoyberg/xml.git
git clone https://github.com/snoyberg/yaml.git
git clone https://github.com/snoyberg/yesod-fay
git clone https://github.com/snoyberg/yesod-js.git
git clone https://github.com/snoyberg/yesoddocs.git
git clone https://github.com/tanakh/html2hamlet.git
git clone https://github.com/technomancy/leiningen.git
git clone https://github.com/thoughtpolice/vacuum.git
git clone https://github.com/tibbe/benchpress.git
git clone https://github.com/tibbe/cassava.git
git clone https://github.com/tibbe/ekg.git
git clone https://github.com/tibbe/haskell-style-guide.git
git clone https://github.com/tibbe/unordered-containers.git
git clone https://github.com/tranma/falling-turnip.git
git clone https://github.com/trogdoro/xiki.git
git clone https://github.com/ujihisa/neco-ghc.git
git clone https://github.com/vincenthz/gtk2hs.git
git clone https://github.com/yav/graphmod.git
git clone https://github.com/yesodweb/Shelly.hs.git
git clone https://github.com/yesodweb/cabal-meta.git
git clone https://github.com/yesodweb/yesod.git
git clone https://github.com/yesodweb/yesodweb.com-content.git
git clone https://github.com/yogsototh/mandelbrot.git
